### ISSUE TITLE
Register?

### ISSUE THREAD

**Issue by tlienart** [meggart/SentinelMissings.jl#1]
Hello! this package is very useful in an environment such as MLJ's but in order to work well with it, it would need to be registered and it doesn't look like it is.

Would you mind registering the package? thanks!

**Comment by meggart** [comment]
Ok I just made the PR. https://github.com/JuliaRegistries/General/pull/5113#issuecomment-550200250

**Comment by tlienart** [comment]
Thanks! given that I don't think you intend to change the API much, just set the version number to  1.0? (and that will help satisfy the automatic registrator)

**Comment by meggart** [comment]
Ok, the PR was just merged and version 1.0 was tagged.

**Comment by tlienart** [comment]
thanks!
